### ISSUE TITLE
trying to fix the active scaffold export plugin

### ISSUE THREAD

**Issue by bretweinraub** [activescaffold/active_scaffold_export#2]
I working in Rails 5.1, and the export plugin stopped working a few year ago.

Actually making good progress, but I see formulations like this:

```
    def export_columns
      @export_columns = active_scaffold_config.export.columns.reject { |col| params[:export_columns][col.name.to_sym].nil? }
      sorting = active_scaffold_config.list.user.sorting || active_scaffold_config.list.sorting
      sorting_columns = sorting.reject { |col, _| @export_columns.include?(col) }.map(&:first)
      @export_columns + sorting_columns
    end
```

things like that don't work anymore because I know

    columns.each has been replaced by columns.each_column.

but there's no formulation for reject.

Some pertinent details
export is an instance of:
```ruby
module ActiveScaffold::Config
  class Export < ActiveScaffold::Config::Form

    def columns
      self.columns = @core.columns._inheritable unless @columns
      @columns
    end
```

any clues how to port legacy code that use the core columns code like a regular array?

**Comment by scambra** [comment]
@naaano Can you add me as owner in rubygems.org? Or you can release 3.4.0 from this repository, I have added you to this repository.

**Comment by scambra** [comment]
3.4.0 released
