### ISSUE TITLE
ActionController::UnknownFormat in XXXController#export

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold_export#3]
The first time I try to do an export after start rails server, I get the error below.  Works fine on subsequent requests.  

Using
gem 'active_scaffold', '~> 3.6.0.rc2'
gem 'rails', '~> 6.0'
git 'https://github.com/activescaffold/active_scaffold_export/', branch: 'master' do
  gem 'active_scaffold_export'
end

---

Extracted source (around line #216):
`
       response.call if response
      else
        raise ActionController::UnknownFormat
      end
    end
`
`
Rails.root: /Users/dbulgatz/AMA/t3-mis

Application Trace | Framework Trace | Full Trace
actionpack (6.0.3.4) lib/action_controller/metal/mime_responds.rb:216:in `respond_to' 
active_scaffold_export (6938d6aabdb5) lib/active_scaffold/actions/export.rb:56:in `export' 
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action' 
actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action' 
actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action' 
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action' 
activesupport (6.0.3.4) lib/active_support/callbacks.rb:112:in `block in run_callbacks' 
active_scaffold (3.6.0.rc2) lib/active_scaffold/actions/core.rb:311:in `clear_storage' 
activesupport (6.0.3.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks' 
activesupport (6.0.3.4) lib/active_support/callbacks.rb:139:in `run_callbacks' 
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action' 
actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action' 
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action' 
activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument' 
activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument' 
activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument' 
actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action' 
actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action' 
activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action' 
actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process' 
actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process' 
actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch' 
actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch' 
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch' 
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve' 
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve' 
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each' 
actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve' 
actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call' 
warden (1.2.9) lib/warden/manager.rb:36:in `block in call' 
warden (1.2.9) lib/warden/manager.rb:34:in `catch' 
warden (1.2.9) lib/warden/manager.rb:34:in `call' 
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call' 
rack (2.2.3) lib/rack/etag.rb:27:in `call' 
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call' 
rack (2.2.3) lib/rack/head.rb:12:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call' 
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context' 
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call' 
activerecord (6.0.3.4) lib/active_record/migration.rb:567:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call' 
activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call' 
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app' 
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call' 
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch' 
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call' 
railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app' 
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call' 
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged' 
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged' 
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged' 
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call' 
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call' 
rack (2.2.3) lib/rack/method_override.rb:24:in `call' 
rack (2.2.3) lib/rack/runtime.rb:22:in `call' 
activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call' 
rack (2.2.3) lib/rack/sendfile.rb:110:in `call' 
actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:82:in `call' 
railties (6.0.3.4) lib/rails/engine.rb:527:in `call' 
puma (5.0.4) lib/puma/configuration.rb:239:in `call' 
puma (5.0.4) lib/puma/request.rb:76:in `block in handle_request' 
puma (5.0.4) lib/puma/thread_pool.rb:337:in `with_force_shutdown' 
puma (5.0.4) lib/puma/request.rb:75:in `handle_request' 
puma (5.0.4) lib/puma/server.rb:430:in `process_client' 
puma (5.0.4) lib/puma/thread_pool.rb:145:in `block in spawn_thread' 
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"w/B7DlHdP/HaOT4+Rqg7vJopTlqW+vlQnc+9pA/EBSsu/v5y3gOZytGREFn2cUKzdGXNXdYuT3mwjl+EhoRx3w==",
 "export_columns"=>
  {"clin"=>"1",
   "discipline"=>"1",
   "tdn_number"=>"1",
   "title"=>"1",
   "sub_tdn_numbers"=>"1",
   "sub_tdn_titles"=>"1",
   "pop_begin"=>"1",
   "pop_end"=>"1",
   "tpoc"=>"1",
   "tpoc_email"=>"1",
   "org_code"=>"1",
   "ordinal"=>"1",
   "ama_sdm"=>"1",
   "updated_by"=>"1",
   "is_latest"=>"1",
   "rev"=>"1",
   "rev_siblings"=>"1"},
 "delimiter"=>",",
 "full_download"=>"true",
 "format"=>"xlsx",
 "commit"=>"Export"}
`

**Comment by scambra** [comment]
Code handling supported formats have been improved
