### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by dennisbulgatz** [activescaffold/active_scaffold_export#4]
undefined method `match' for nil:NilClass

Extracted source (around line #458):

elsif v.to_s =~ Axlsx::SAFE_FLOAT_REGEX && v.respond_to?(:to_f)
        :float
      elsif (matchdata = v.to_s.match(MAYBE_FLOAT_REGEX)) && (Float::MIN_10_EXP..Float::MAX_10_EXP).cover?(matchdata[:exp].to_i) && v.respond_to?(:to_f)
        :float
      elsif v.to_s =~ Axlsx::ISO_8601_REGEX
        :iso_8601

Rails.root: /Users/dbulgatz/t3mis

Application Trace | Framework Trace | Full Trace
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/cell.rb:458:in `cell_type_from_value'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/cell.rb:42:in `initialize'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:159:in `new'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:159:in `block in array_to_cells'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:153:in `each'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:153:in `each_with_index'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:153:in `array_to_cells'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/row.rb:36:in `initialize'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/worksheet.rb:412:in `new'
caxlsx (3.1.1) lib/axlsx/workbook/worksheet/worksheet.rb:412:in `add_row'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:77:in `block (5 levels) in export'
activerecord (6.1.4.1) lib/active_record/relation/delegation.rb:88:in `each'
activerecord (6.1.4.1) lib/active_record/relation/delegation.rb:88:in `each'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:76:in `block (4 levels) in export'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:117:in `block in find_items_for_export'
active_scaffold (3.6.3) lib/active_scaffold/paginator.rb:46:in `block in each'
active_scaffold (3.6.3) lib/active_scaffold/paginator.rb:53:in `block in each_with_index'
active_scaffold (3.6.3) lib/active_scaffold/paginator.rb:52:in `upto'
active_scaffold (3.6.3) lib/active_scaffold/paginator.rb:52:in `each_with_index'
active_scaffold (3.6.3) lib/active_scaffold/paginator.rb:45:in `each'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:116:in `find_items_for_export'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:75:in `block (3 levels) in export'
caxlsx (3.1.1) lib/axlsx/workbook/workbook.rb:270:in `add_worksheet'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:73:in `block (2 levels) in export'
actionpack (6.1.4.1) lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
active_scaffold_export (e5cda70dee3d) lib/active_scaffold/actions/export.rb:56:in `export'
actionpack (6.1.4.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.4.1) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.4.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
active_scaffold (3.6.3) lib/active_scaffold/actions/core.rb:311:in `clear_storage'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
actiontext (6.1.4.1) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (6.1.4.1) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.4.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.4.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.4.1) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.4.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.4.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.4.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.4.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.4.1) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.1) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
railties (6.1.4.1) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"Xx/u5nZFzRt1LKEI4GbojZZr9dPS5KCU1C2Q9sg61kXGgdLMOstVahD0A4j7m5lSDjvh/2BCRN+LUag73cZP0Q==",
 "export_columns"=>
  {"clin"=>"1",
   "discipline"=>"1",
   "tdn"=>"1",
   "tdn_title"=>"1",
   "sub_tdn_number"=>"1",
   "sub_tdn_title"=>"1",
   "description"=>"1",
   "due_date"=>"1",
   "tpoc"=>"1",
   "tpoc_email"=>"1",
   "org_code"=>"1",
   "work_lead"=>"1",
   "work_lead_email"=>"1",
   "comments"=>"1"},
 "delimiter"=>",",
 "full_download"=>"true",
 "format"=>"xlsx",
 "commit"=>"Export"}

**Comment by scambra** [comment]
Exception is raised in other gem
