### ISSUE TITLE
ActionView::MissingTemplate

### ISSUE THREAD

**Issue by CCH4GITHUB** [activescaffold/active_scaffold_export#6]
gem 'active_scaffold_export'
gem 'axlsx_rails'

bundle install. Add to application.css:
 *= require active_scaffold_export

class UsersController < ApplicationController
  active_scaffold :"user" do |conf|
    conf.actions.add :export
    # you can filter or sort columns if you want
    conf.export.columns = %w(username email level active) 
    # you can define a default values for the exporting form
    conf.export.default_deselected_columns = %w(active)
    conf.export.default_delimiter = ";"
    conf.export.force_quotes = "true"  
  end
end

when click Export btn
http://127.0.0.1:3000/users/show_export
ActionView::MissingTemplate (Missing partial #<Proc:0x000001372a20a118 C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/actionview-7.0.2.3/lib/action_view/_layouts.rb:389> with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder, :axlsx]}.  

How to deal with the Missing Template issue ?

**Comment by scambra** [comment]
Better to use caxlsx_rails. Detect for supported formats have been improved to prevent issues like this one
